# Generated by Django 5.0.2 on 2024-04-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecondModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_field', models.CharField(max_length=100)),
                ('first_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestProject.firstmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_field', models.CharField(max_length=100)),
                ('second_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestProject.secondmodel')),
            ],
        ),
    ]
